// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2mJ3_dF8KYJYTzevvg4K_F7hzzDtm34',
    appId: '1:125173837995:web:2cbb77b76947dcc1c707ee',
    messagingSenderId: '125173837995',
    projectId: 'ffl-pro-app',
    authDomain: 'ffl-pro-app.firebaseapp.com',
    storageBucket: 'ffl-pro-app.firebasestorage.app',
    measurementId: 'G-J3MCXZJSF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1KuH86TtB80XWTnqNZlXxe2HMCz22HLQ',
    appId: '1:125173837995:android:a1bec19ccaa9d436c707ee',
    messagingSenderId: '125173837995',
    projectId: 'ffl-pro-app',
    storageBucket: 'ffl-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtWeFneQia-9bJEQYYGYPQsBXP7bQe7k',
    appId: '1:125173837995:ios:0a5a42090760c430c707ee',
    messagingSenderId: '125173837995',
    projectId: 'ffl-pro-app',
    storageBucket: 'ffl-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.fflProApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGtWeFneQia-9bJEQYYGYPQsBXP7bQe7k',
    appId: '1:125173837995:ios:0a5a42090760c430c707ee',
    messagingSenderId: '125173837995',
    projectId: 'ffl-pro-app',
    storageBucket: 'ffl-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.fflProApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2mJ3_dF8KYJYTzevvg4K_F7hzzDtm34',
    appId: '1:125173837995:web:cc9d97c7cc70f2b0c707ee',
    messagingSenderId: '125173837995',
    projectId: 'ffl-pro-app',
    authDomain: 'ffl-pro-app.firebaseapp.com',
    storageBucket: 'ffl-pro-app.firebasestorage.app',
    measurementId: 'G-B57MRLSDP1',
  );
}
